- task: NodeTool@0
  inputs:
    checkLatest: true

- task: npmAuthenticate@0
  displayName: 'Authenticate to Azure Artifacts feed'
  inputs:
    workingFile: .npmrc
    customEndpoint: npm-artifacts-connection


- script: |
   npm publish  
  displayName: Publish